INSERT INTO JOBSAMPLEUSER.TB_BOARD (BOARD_NO,REGDATE,REGUSER,MODDATE,MODUSER,BOARD_NAME,BOARD_KIND_CODE,BOARD_REPLY_FUNC_YN) VALUES
	 (1,NULL,NULL,NULL,NULL,'일반 게시판 01','01','N'),
	 (2,NULL,NULL,NULL,NULL,'FAQ 게시판 01','02','N'),
	 (3,NULL,NULL,NULL,NULL,'답변형 게시판 01','04','N');
