INSERT INTO JOBSAMPLEUSER.TB_SYS_CODE (SYS_CODE_GROUP,REGDATE,REGUSER,MODDATE,MODUSER,SYS_CODE,SYS_CODE_NAME,SYS_CODE_DESC) VALUES
	 ('BOARD_KIND_CODE',NULL,NULL,NULL,NULL,'01','일반 게시판','일반 게시판'),
	 ('BOARD_KIND_CODE',NULL,NULL,NULL,NULL,'02','FAQ 게시판','FAQ 게시판'),
	 ('BOARD_KIND_CODE',NULL,NULL,NULL,NULL,'03','계층형 게시판','계층형 게시판'),
	 ('BOARD_KIND_CODE',NULL,NULL,NULL,NULL,'04','답변형 게시판','답변형 게시판'),
	 ('BOARD_KIND_CODE',NULL,NULL,NULL,NULL,'05','이미지 게시판','이미지 게시판'),
	 ('BOARD_KIND_CODE',NULL,NULL,NULL,NULL,'06','블로그형 게시판','블로그형 게시판');
